Fixes a conflict with easy_thumbnails's thumbnail generation
This error is fixed:
```
File ".../site-packages/easy_thumbnails/source_generators.py", line 30, in pil_image
    source = BytesIO(source.read())
TypeError: 'str' does not support the buffer interface
```